// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService AI 服务（Wails 暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} callID
 * @returns {$CancellablePromise<void>}
 */
export function ApproveTool(callID) {
    return $Call.ByID(4107800528, callID);
}

/**
 * CancelProcessing 取消当前处理
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function CancelProcessing(connID) {
    return $Call.ByID(3774016508, connID);
}

/**
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function ClearChatHistory(connID) {
    return $Call.ByID(2121909568, connID);
}

/**
 * @param {string} callID
 * @returns {$CancellablePromise<void>}
 */
export function DenyTool(callID) {
    return $Call.ByID(771246085, callID);
}

/**
 * FetchModels 从 API 端点获取可用模型列表（使用已保存的配置）
 * @returns {$CancellablePromise<{ [_ in string]?: string }[]>}
 */
export function FetchModels() {
    return $Call.ByID(4014342029).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FetchModelsWithParams 从指定的 API 端点获取可用模型列表（使用传入的参数，不依赖已保存的配置）
 * @param {string} endpoint
 * @param {string} key
 * @returns {$CancellablePromise<{ [_ in string]?: string }[]>}
 */
export function FetchModelsWithParams(endpoint, key) {
    return $Call.ByID(2357153351, endpoint, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} connID
 * @returns {$CancellablePromise<($models.ChatMessage | null)[]>}
 */
export function GetChatHistory(connID) {
    return $Call.ByID(1326461607, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AIConfig | null>}
 */
export function GetConfig() {
    return $Call.ByID(118284705).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsConfigured() {
    return $Call.ByID(2824451185);
}

/**
 * @param {$models.AIConfig | null} c
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(c) {
    return $Call.ByID(2313591426, c);
}

/**
 * @param {$models.ChatRequest | null} req
 * @returns {$CancellablePromise<$models.ChatResponse | null>}
 */
export function SendMessage(req) {
    return $Call.ByID(2405239018, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3027214994, app);
}

/**
 * @param {string} callID
 * @param {string} result
 * @returns {$CancellablePromise<void>}
 */
export function SubmitToolResult(callID, result) {
    return $Call.ByID(3522079410, callID, result);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ChatMessage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.AIConfig.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.ChatResponse.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
