// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 配置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportConfig 导出配置
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig() {
    return $Call.ByID(3283886273);
}

/**
 * Get 获取单个配置项
 * @param {string} category
 * @param {string} key
 * @returns {$CancellablePromise<any>}
 */
export function Get(category, key) {
    return $Call.ByID(3552556231, category, key);
}

/**
 * GetAIConfig 获取 AI 配置（预留，供 Wails 绑定）
 * @returns {$CancellablePromise<$models.AIConfig>}
 */
export function GetAIConfig() {
    return $Call.ByID(2187301699).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetConfig 获取完整配置
 * @returns {$CancellablePromise<$models.AppConfig | null>}
 */
export function GetConfig() {
    return $Call.ByID(568370053).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetFileManagerConfig 获取文件管理配置（预留，供 Wails 绑定）
 * @returns {$CancellablePromise<$models.FileManagerConfig>}
 */
export function GetFileManagerConfig() {
    return $Call.ByID(2336134806).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSSHSettings 获取 SSH 设置（预留，供 Wails 绑定）
 * @returns {$CancellablePromise<$models.SSHSettings>}
 */
export function GetSSHSettings() {
    return $Call.ByID(4134726434).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetTerminalConfig 获取终端配置
 * @returns {$CancellablePromise<$models.TerminalConfig>}
 */
export function GetTerminalConfig() {
    return $Call.ByID(2517133609).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetUIConfig 获取界面配置
 * @returns {$CancellablePromise<$models.UIConfig>}
 */
export function GetUIConfig() {
    return $Call.ByID(3861792735).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ImportConfig 导入配置
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function ImportConfig(jsonStr) {
    return $Call.ByID(1869735490, jsonStr);
}

/**
 * ResetAll 重置所有配置
 * @returns {$CancellablePromise<void>}
 */
export function ResetAll() {
    return $Call.ByID(3575431267);
}

/**
 * ResetCategory 重置分类配置
 * @param {string} category
 * @returns {$CancellablePromise<void>}
 */
export function ResetCategory(category) {
    return $Call.ByID(4182599240, category);
}

/**
 * Set 设置单个配置项
 * @param {string} category
 * @param {string} key
 * @param {any} value
 * @returns {$CancellablePromise<void>}
 */
export function Set(category, key, value) {
    return $Call.ByID(2825066771, category, key, value);
}

/**
 * SetAIConfig 设置 AI 配置（预留）
 * @param {$models.AIConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SetAIConfig(config) {
    return $Call.ByID(3903119391, config);
}

/**
 * SetApp 设置应用实例
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1815052230, app);
}

/**
 * SetConfig 设置完整配置
 * @param {$models.AppConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function SetConfig(config) {
    return $Call.ByID(1662437425, config);
}

/**
 * SetFileManagerConfig 设置文件管理配置（预留）
 * @param {$models.FileManagerConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SetFileManagerConfig(config) {
    return $Call.ByID(3071552898, config);
}

/**
 * SetSSHSettings 设置 SSH 设置（预留）
 * @param {$models.SSHSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SetSSHSettings(settings) {
    return $Call.ByID(1497002334, settings);
}

/**
 * SetTerminalConfig 设置终端配置
 * @param {$models.TerminalConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SetTerminalConfig(config) {
    return $Call.ByID(3138365, config);
}

/**
 * SetUIConfig 设置界面配置（预留）
 * @param {$models.UIConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SetUIConfig(config) {
    return $Call.ByID(2653085827, config);
}

// Private type creation functions
const $$createType0 = $models.AIConfig.createFrom;
const $$createType1 = $models.AppConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.FileManagerConfig.createFrom;
const $$createType4 = $models.SSHSettings.createFrom;
const $$createType5 = $models.TerminalConfig.createFrom;
const $$createType6 = $models.UIConfig.createFrom;
