// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FirewallService 防火墙管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFirewalldRule 添加 firewalld 规则
 * @param {string} connID
 * @param {string} zone
 * @param {string} port
 * @param {string} protocol
 * @returns {$CancellablePromise<void>}
 */
export function AddFirewalldRule(connID, zone, port, protocol) {
    return $Call.ByID(1147310980, connID, zone, port, protocol);
}

/**
 * AddIptablesRule 添加 iptables 规则
 * @param {string} connID
 * @param {string} chain
 * @param {string} target
 * @param {string} protocol
 * @param {string} port
 * @param {string} source
 * @param {string} comment
 * @returns {$CancellablePromise<void>}
 */
export function AddIptablesRule(connID, chain, target, protocol, port, source, comment) {
    return $Call.ByID(2979184888, connID, chain, target, protocol, port, source, comment);
}

/**
 * AddRule 添加规则（根据防火墙类型自动适配）
 * @param {string} connID
 * @param {string} chain
 * @param {string} target
 * @param {string} protocol
 * @param {string} port
 * @param {string} source
 * @param {string} comment
 * @returns {$CancellablePromise<void>}
 */
export function AddRule(connID, chain, target, protocol, port, source, comment) {
    return $Call.ByID(3720463264, connID, chain, target, protocol, port, source, comment);
}

/**
 * AddUfwRule 添加 ufw 规则
 * @param {string} connID
 * @param {string} action
 * @param {string} port
 * @param {string} protocol
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function AddUfwRule(connID, action, port, protocol, source) {
    return $Call.ByID(104072072, connID, action, port, protocol, source);
}

/**
 * DeleteFirewalldRule 删除 firewalld 规则
 * @param {string} connID
 * @param {string} zone
 * @param {string} port
 * @param {string} protocol
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFirewalldRule(connID, zone, port, protocol) {
    return $Call.ByID(1545592514, connID, zone, port, protocol);
}

/**
 * DeleteIptablesRule 删除 iptables 规则
 * @param {string} connID
 * @param {string} chain
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function DeleteIptablesRule(connID, chain, index) {
    return $Call.ByID(1347201862, connID, chain, index);
}

/**
 * DeleteRule 删除规则（根据防火墙类型自动适配）
 * @param {string} connID
 * @param {string} chain
 * @param {number} index
 * @param {string} port
 * @param {string} protocol
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRule(connID, chain, index, port, protocol) {
    return $Call.ByID(1165422686, connID, chain, index, port, protocol);
}

/**
 * DeleteUfwRule 删除 ufw 规则
 * @param {string} connID
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function DeleteUfwRule(connID, index) {
    return $Call.ByID(577875178, connID, index);
}

/**
 * GetFirewallInfo 获取防火墙信息
 * @param {string} connID
 * @returns {$CancellablePromise<$models.FirewallInfo | null>}
 */
export function GetFirewallInfo(connID) {
    return $Call.ByID(3303526385, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RunCustomCommand 执行自定义防火墙命令
 * @param {string} connID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function RunCustomCommand(connID, command) {
    return $Call.ByID(3674046492, connID, command);
}

/**
 * ToggleFirewall 启用/禁用防火墙
 * @param {string} connID
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFirewall(connID, enable) {
    return $Call.ByID(1092045575, connID, enable);
}

/**
 * ToggleUfw 启用/禁用 ufw
 * @param {string} connID
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function ToggleUfw(connID, enable) {
    return $Call.ByID(2691831621, connID, enable);
}

// Private type creation functions
const $$createType0 = $models.FirewallInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
