// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetAppName 获取应用名称
 * @returns {$CancellablePromise<string>}
 */
export function GetAppName() {
    return $Call.ByID(2258410938);
}

/**
 * GetVersion 获取软件版本
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(2969803278);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(3121721795, name);
}
