// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * CPUStats CPU 统计
 */
export class CPUStats {
    /**
     * Creates a new CPUStats instance.
     * @param {Partial<CPUStats>} [$$source = {}] - The source object to create the CPUStats.
     */
    constructor($$source = {}) {
        if (!("usagePercent" in $$source)) {
            /**
             * 使用率 %
             * @member
             * @type {number}
             */
            this["usagePercent"] = 0;
        }
        if (!("cores" in $$source)) {
            /**
             * 核心数
             * @member
             * @type {number}
             */
            this["cores"] = 0;
        }
        if (!("perCpuUsage" in $$source)) {
            /**
             * 每个核心的使用率
             * @member
             * @type {number[]}
             */
            this["perCpuUsage"] = [];
        }
        if (!("loadAvg" in $$source)) {
            /**
             * 平均负载
             * @member
             * @type {LoadAvg}
             */
            this["loadAvg"] = (new LoadAvg());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CPUStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CPUStats}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perCpuUsage" in $$parsedSource) {
            $$parsedSource["perCpuUsage"] = $$createField2_0($$parsedSource["perCpuUsage"]);
        }
        if ("loadAvg" in $$parsedSource) {
            $$parsedSource["loadAvg"] = $$createField3_0($$parsedSource["loadAvg"]);
        }
        return new CPUStats(/** @type {Partial<CPUStats>} */($$parsedSource));
    }
}

/**
 * CommandResult 命令执行结果
 */
export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("stdout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stderr"] = "";
        }
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

/**
 * ConnectionInfo SSH连接信息
 */
export class ConnectionInfo {
    /**
     * Creates a new ConnectionInfo instance.
     * @param {Partial<ConnectionInfo>} [$$source = {}] - The source object to create the ConnectionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keyPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("saved" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["saved"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group_id"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo(/** @type {Partial<ConnectionInfo>} */($$parsedSource));
    }
}

/**
 * DiskIOStats 磁盘 IO 统计
 */
export class DiskIOStats {
    /**
     * Creates a new DiskIOStats instance.
     * @param {Partial<DiskIOStats>} [$$source = {}] - The source object to create the DiskIOStats.
     */
    constructor($$source = {}) {
        if (!("readBytes" in $$source)) {
            /**
             * 读取字节数
             * @member
             * @type {number}
             */
            this["readBytes"] = 0;
        }
        if (!("writeBytes" in $$source)) {
            /**
             * 写入字节数
             * @member
             * @type {number}
             */
            this["writeBytes"] = 0;
        }
        if (!("readCount" in $$source)) {
            /**
             * 读取次数
             * @member
             * @type {number}
             */
            this["readCount"] = 0;
        }
        if (!("writeCount" in $$source)) {
            /**
             * 写入次数
             * @member
             * @type {number}
             */
            this["writeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskIOStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskIOStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskIOStats(/** @type {Partial<DiskIOStats>} */($$parsedSource));
    }
}

/**
 * DiskPartition 磁盘分区
 */
export class DiskPartition {
    /**
     * Creates a new DiskPartition instance.
     * @param {Partial<DiskPartition>} [$$source = {}] - The source object to create the DiskPartition.
     */
    constructor($$source = {}) {
        if (!("device" in $$source)) {
            /**
             * 设备名
             * @member
             * @type {string}
             */
            this["device"] = "";
        }
        if (!("mountpoint" in $$source)) {
            /**
             * 挂载点
             * @member
             * @type {string}
             */
            this["mountpoint"] = "";
        }
        if (!("fstype" in $$source)) {
            /**
             * 文件系统类型
             * @member
             * @type {string}
             */
            this["fstype"] = "";
        }
        if (!("total" in $$source)) {
            /**
             * 总容量 (bytes)
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("used" in $$source)) {
            /**
             * 已使用 (bytes)
             * @member
             * @type {number}
             */
            this["used"] = 0;
        }
        if (!("free" in $$source)) {
            /**
             * 空闲 (bytes)
             * @member
             * @type {number}
             */
            this["free"] = 0;
        }
        if (!("usedPercent" in $$source)) {
            /**
             * 使用率 %
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskPartition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskPartition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiskPartition(/** @type {Partial<DiskPartition>} */($$parsedSource));
    }
}

/**
 * DiskStats 磁盘统计
 */
export class DiskStats {
    /**
     * Creates a new DiskStats instance.
     * @param {Partial<DiskStats>} [$$source = {}] - The source object to create the DiskStats.
     */
    constructor($$source = {}) {
        if (!("partitions" in $$source)) {
            /**
             * 分区列表
             * @member
             * @type {DiskPartition[]}
             */
            this["partitions"] = [];
        }
        if (!("ioStats" in $$source)) {
            /**
             * IO 统计
             * @member
             * @type {DiskIOStats}
             */
            this["ioStats"] = (new DiskIOStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiskStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiskStats}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("partitions" in $$parsedSource) {
            $$parsedSource["partitions"] = $$createField0_0($$parsedSource["partitions"]);
        }
        if ("ioStats" in $$parsedSource) {
            $$parsedSource["ioStats"] = $$createField1_0($$parsedSource["ioStats"]);
        }
        return new DiskStats(/** @type {Partial<DiskStats>} */($$parsedSource));
    }
}

/**
 * FileInfo 文件信息结构体
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("owner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * FirewallInfo 防火墙信息
 */
export class FirewallInfo {
    /**
     * Creates a new FirewallInfo instance.
     * @param {Partial<FirewallInfo>} [$$source = {}] - The source object to create the FirewallInfo.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * iptables / firewalld / ufw / unknown
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * active / inactive / unknown
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("rules" in $$source)) {
            /**
             * @member
             * @type {FirewallRule[]}
             */
            this["rules"] = [];
        }
        if (!("rawOutput" in $$source)) {
            /**
             * 原始输出
             * @member
             * @type {string}
             */
            this["rawOutput"] = "";
        }
        if (!("chains" in $$source)) {
            /**
             * 可用的链/区域
             * @member
             * @type {string[]}
             */
            this["chains"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirewallInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FirewallInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        if ("chains" in $$parsedSource) {
            $$parsedSource["chains"] = $$createField4_0($$parsedSource["chains"]);
        }
        return new FirewallInfo(/** @type {Partial<FirewallInfo>} */($$parsedSource));
    }
}

/**
 * FirewallRule 防火墙规则
 */
export class FirewallRule {
    /**
     * Creates a new FirewallRule instance.
     * @param {Partial<FirewallRule>} [$$source = {}] - The source object to create the FirewallRule.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * 规则序号
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("chain" in $$source)) {
            /**
             * INPUT / OUTPUT / FORWARD / zone
             * @member
             * @type {string}
             */
            this["chain"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * ACCEPT / DROP / REJECT / allow / deny
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * tcp / udp / icmp / all
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 源地址
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("dest" in $$source)) {
            /**
             * 目标地址
             * @member
             * @type {string}
             */
            this["dest"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * 端口
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * 备注
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * 原始行
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FirewallRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FirewallRule}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FirewallRule(/** @type {Partial<FirewallRule>} */($$parsedSource));
    }
}

/**
 * GuardianProcess 守护进程信息
 */
export class GuardianProcess {
    /**
     * Creates a new GuardianProcess instance.
     * @param {Partial<GuardianProcess>} [$$source = {}] - The source object to create the GuardianProcess.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("workDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workDir"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * running / stopped / failed / unknown
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("autoRestart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoRestart"] = false;
        }
        if (!("logPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logPath"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("restarts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restarts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GuardianProcess instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GuardianProcess}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GuardianProcess(/** @type {Partial<GuardianProcess>} */($$parsedSource));
    }
}

/**
 * LoadAvg 平均负载
 */
export class LoadAvg {
    /**
     * Creates a new LoadAvg instance.
     * @param {Partial<LoadAvg>} [$$source = {}] - The source object to create the LoadAvg.
     */
    constructor($$source = {}) {
        if (!("load1" in $$source)) {
            /**
             * 1分钟
             * @member
             * @type {number}
             */
            this["load1"] = 0;
        }
        if (!("load5" in $$source)) {
            /**
             * 5分钟
             * @member
             * @type {number}
             */
            this["load5"] = 0;
        }
        if (!("load15" in $$source)) {
            /**
             * 15分钟
             * @member
             * @type {number}
             */
            this["load15"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadAvg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadAvg}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadAvg(/** @type {Partial<LoadAvg>} */($$parsedSource));
    }
}

/**
 * MemoryStats 内存统计
 */
export class MemoryStats {
    /**
     * Creates a new MemoryStats instance.
     * @param {Partial<MemoryStats>} [$$source = {}] - The source object to create the MemoryStats.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * 总内存 (bytes)
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("used" in $$source)) {
            /**
             * 已使用 (bytes)
             * @member
             * @type {number}
             */
            this["used"] = 0;
        }
        if (!("free" in $$source)) {
            /**
             * 空闲 (bytes)
             * @member
             * @type {number}
             */
            this["free"] = 0;
        }
        if (!("usedPercent" in $$source)) {
            /**
             * 使用率 %
             * @member
             * @type {number}
             */
            this["usedPercent"] = 0;
        }
        if (!("cached" in $$source)) {
            /**
             * 缓存 (bytes)
             * @member
             * @type {number}
             */
            this["cached"] = 0;
        }
        if (!("swapTotal" in $$source)) {
            /**
             * 交换区总大小
             * @member
             * @type {number}
             */
            this["swapTotal"] = 0;
        }
        if (!("swapUsed" in $$source)) {
            /**
             * 交换区已使用
             * @member
             * @type {number}
             */
            this["swapUsed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MemoryStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryStats(/** @type {Partial<MemoryStats>} */($$parsedSource));
    }
}

/**
 * NetInterface 网络接口
 */
export class NetInterface {
    /**
     * Creates a new NetInterface instance.
     * @param {Partial<NetInterface>} [$$source = {}] - The source object to create the NetInterface.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 接口名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("bytesSent" in $$source)) {
            /**
             * 发送字节
             * @member
             * @type {number}
             */
            this["bytesSent"] = 0;
        }
        if (!("bytesRecv" in $$source)) {
            /**
             * 接收字节
             * @member
             * @type {number}
             */
            this["bytesRecv"] = 0;
        }
        if (!("packetsSent" in $$source)) {
            /**
             * 发送包数
             * @member
             * @type {number}
             */
            this["packetsSent"] = 0;
        }
        if (!("packetsRecv" in $$source)) {
            /**
             * 接收包数
             * @member
             * @type {number}
             */
            this["packetsRecv"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetInterface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetInterface}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetInterface(/** @type {Partial<NetInterface>} */($$parsedSource));
    }
}

/**
 * NetworkStats 网络统计
 */
export class NetworkStats {
    /**
     * Creates a new NetworkStats instance.
     * @param {Partial<NetworkStats>} [$$source = {}] - The source object to create the NetworkStats.
     */
    constructor($$source = {}) {
        if (!("interfaces" in $$source)) {
            /**
             * 网络接口列表
             * @member
             * @type {NetInterface[]}
             */
            this["interfaces"] = [];
        }
        if (!("totalRx" in $$source)) {
            /**
             * 总接收字节
             * @member
             * @type {number}
             */
            this["totalRx"] = 0;
        }
        if (!("totalTx" in $$source)) {
            /**
             * 总发送字节
             * @member
             * @type {number}
             */
            this["totalTx"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkStats}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField0_0($$parsedSource["interfaces"]);
        }
        return new NetworkStats(/** @type {Partial<NetworkStats>} */($$parsedSource));
    }
}

/**
 * PortForward 端口转发规则
 */
export class PortForward {
    /**
     * Creates a new PortForward instance.
     * @param {Partial<PortForward>} [$$source = {}] - The source object to create the PortForward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "local" / "remote"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("bindAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bindAddr"] = "";
        }
        if (!("bindPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bindPort"] = 0;
        }
        if (!("remoteHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteHost"] = "";
        }
        if (!("remotePort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remotePort"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * "running" / "stopped" / "error"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("activeConns" in $$source)) {
            /**
             * 流量统计
             * 当前活跃连接数
             * @member
             * @type {number}
             */
            this["activeConns"] = 0;
        }
        if (!("totalConns" in $$source)) {
            /**
             * 历史总连接数
             * @member
             * @type {number}
             */
            this["totalConns"] = 0;
        }
        if (!("bytesSent" in $$source)) {
            /**
             * 发送字节数（上行）
             * @member
             * @type {number}
             */
            this["bytesSent"] = 0;
        }
        if (!("bytesRecv" in $$source)) {
            /**
             * 接收字节数（下行）
             * @member
             * @type {number}
             */
            this["bytesRecv"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortForward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortForward(/** @type {Partial<PortForward>} */($$parsedSource));
    }
}

/**
 * ProcessInfo 进程信息
 */
export class ProcessInfo {
    /**
     * Creates a new ProcessInfo instance.
     * @param {Partial<ProcessInfo>} [$$source = {}] - The source object to create the ProcessInfo.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * 进程 ID
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * 进程名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            /**
             * CPU 使用率 %
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memPercent" in $$source)) {
            /**
             * 内存使用率 %
             * @member
             * @type {number}
             */
            this["memPercent"] = 0;
        }
        if (!("memRss" in $$source)) {
            /**
             * 物理内存使用 (bytes)
             * @member
             * @type {number}
             */
            this["memRss"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * 进程状态
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * 用户名
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * 启动时间
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("elapsedTime" in $$source)) {
            /**
             * 运行时长
             * @member
             * @type {string}
             */
            this["elapsedTime"] = "";
        }
        if (!("cmdline" in $$source)) {
            /**
             * 命令行
             * @member
             * @type {string}
             */
            this["cmdline"] = "";
        }
        if (!("numThreads" in $$source)) {
            /**
             * 线程数
             * @member
             * @type {number}
             */
            this["numThreads"] = 0;
        }
        if (!("priority" in $$source)) {
            /**
             * 优先级
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("nice" in $$source)) {
            /**
             * Nice 值
             * @member
             * @type {number}
             */
            this["nice"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo(/** @type {Partial<ProcessInfo>} */($$parsedSource));
    }
}

/**
 * SSHClient SSH客户端结构体
 */
export class SSHClient {
    /**
     * Creates a new SSHClient instance.
     * @param {Partial<SSHClient>} [$$source = {}] - The source object to create the SSHClient.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHClient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHClient}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHClient(/** @type {Partial<SSHClient>} */($$parsedSource));
    }
}

/**
 * SSHConfig SSH连接配置
 */
export class SSHConfig {
    /**
     * Creates a new SSHConfig instance.
     * @param {Partial<SSHConfig>} [$$source = {}] - The source object to create the SSHConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 密钥文件路径（兼容旧版）
             * @member
             * @type {string | undefined}
             */
            this["keyPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 密钥内容（直接输入）
             * @member
             * @type {string | undefined}
             */
            this["privateKey"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["timeout"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig(/** @type {Partial<SSHConfig>} */($$parsedSource));
    }
}

/**
 * SSHGroup SSH分组
 */
export class SSHGroup {
    /**
     * Creates a new SSHGroup instance.
     * @param {Partial<SSHGroup>} [$$source = {}] - The source object to create the SSHGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("conn_ids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["conn_ids"] = [];
        }
        if (!("window_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["window_id"] = "";
        }
        if (!("is_default" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conn_ids" in $$parsedSource) {
            $$parsedSource["conn_ids"] = $$createField2_0($$parsedSource["conn_ids"]);
        }
        return new SSHGroup(/** @type {Partial<SSHGroup>} */($$parsedSource));
    }
}

/**
 * SystemStats 系统整体统计
 */
export class SystemStats {
    /**
     * Creates a new SystemStats instance.
     * @param {Partial<SystemStats>} [$$source = {}] - The source object to create the SystemStats.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("uptime" in $$source)) {
            /**
             * 系统运行时长
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("cpu" in $$source)) {
            /**
             * @member
             * @type {CPUStats}
             */
            this["cpu"] = (new CPUStats());
        }
        if (!("memory" in $$source)) {
            /**
             * @member
             * @type {MemoryStats}
             */
            this["memory"] = (new MemoryStats());
        }
        if (!("disk" in $$source)) {
            /**
             * @member
             * @type {DiskStats}
             */
            this["disk"] = (new DiskStats());
        }
        if (!("network" in $$source)) {
            /**
             * @member
             * @type {NetworkStats}
             */
            this["network"] = (new NetworkStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemStats}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cpu" in $$parsedSource) {
            $$parsedSource["cpu"] = $$createField2_0($$parsedSource["cpu"]);
        }
        if ("memory" in $$parsedSource) {
            $$parsedSource["memory"] = $$createField3_0($$parsedSource["memory"]);
        }
        if ("disk" in $$parsedSource) {
            $$parsedSource["disk"] = $$createField4_0($$parsedSource["disk"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField5_0($$parsedSource["network"]);
        }
        return new SystemStats(/** @type {Partial<SystemStats>} */($$parsedSource));
    }
}

/**
 * WindowManager SSH窗口管理器
 */
export class WindowManager {
    /**
     * Creates a new WindowManager instance.
     * @param {Partial<WindowManager>} [$$source = {}] - The source object to create the WindowManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowManager(/** @type {Partial<WindowManager>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = LoadAvg.createFrom;
const $$createType2 = DiskPartition.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = DiskIOStats.createFrom;
const $$createType5 = FirewallRule.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = NetInterface.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = CPUStats.createFrom;
const $$createType11 = MemoryStats.createFrom;
const $$createType12 = DiskStats.createFrom;
const $$createType13 = NetworkStats.createFrom;
