// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortForwardService 端口转发服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddLocalForward 添加本地端口转发
 * bindPort=0 时由操作系统自动分配可用端口
 * @param {string} connID
 * @param {string} bindAddr
 * @param {number} bindPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @returns {$CancellablePromise<$models.PortForward | null>}
 */
export function AddLocalForward(connID, bindAddr, bindPort, remoteHost, remotePort) {
    return $Call.ByID(1746999042, connID, bindAddr, bindPort, remoteHost, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AddRemoteForward 添加远程端口转发
 * @param {string} connID
 * @param {string} bindAddr
 * @param {number} bindPort
 * @param {string} remoteHost
 * @param {number} remotePort
 * @returns {$CancellablePromise<$models.PortForward | null>}
 */
export function AddRemoteForward(connID, bindAddr, bindPort, remoteHost, remotePort) {
    return $Call.ByID(4024537433, connID, bindAddr, bindPort, remoteHost, remotePort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetForwardStatus 获取单个转发状态
 * @param {string} forwardID
 * @returns {$CancellablePromise<$models.PortForward | null>}
 */
export function GetForwardStatus(forwardID) {
    return $Call.ByID(2437744172, forwardID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetForwards 获取指定连接的所有转发规则
 * @param {string} connID
 * @returns {$CancellablePromise<$models.PortForward[]>}
 */
export function GetForwards(connID) {
    return $Call.ByID(2414620931, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RemoveForward 删除转发规则
 * @param {string} forwardID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveForward(forwardID) {
    return $Call.ByID(2552376828, forwardID);
}

/**
 * StartForward 启动转发
 * @param {string} forwardID
 * @returns {$CancellablePromise<void>}
 */
export function StartForward(forwardID) {
    return $Call.ByID(74948830, forwardID);
}

/**
 * StopAllByConnID 停止指定连接的所有转发
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function StopAllByConnID(connID) {
    return $Call.ByID(3822011316, connID);
}

/**
 * StopForward 停止转发
 * @param {string} forwardID
 * @returns {$CancellablePromise<void>}
 */
export function StopForward(forwardID) {
    return $Call.ByID(3638310128, forwardID);
}

// Private type creation functions
const $$createType0 = $models.PortForward.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
