// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProcessGuardianService 进程守护服务（基于 systemd，兼容所有现代 Linux）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearGuardianLogs 清空守护进程日志（清空 systemd journal 中该服务的记录）
 * @param {string} connID
 * @param {string} name
 * @param {string} logPath
 * @returns {$CancellablePromise<void>}
 */
export function ClearGuardianLogs(connID, name, logPath) {
    return $Call.ByID(313841282, connID, name, logPath);
}

/**
 * CreateGuardian 创建守护进程
 * @param {string} connID
 * @param {string} name
 * @param {string} command
 * @param {string} workDir
 * @param {boolean} autoRestart
 * @returns {$CancellablePromise<void>}
 */
export function CreateGuardian(connID, name, command, workDir, autoRestart) {
    return $Call.ByID(2012152998, connID, name, command, workDir, autoRestart);
}

/**
 * DeleteGuardian 删除守护进程
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGuardian(connID, name) {
    return $Call.ByID(2128534737, connID, name);
}

/**
 * GetGuardianLogs 获取守护进程日志（从 systemd journal 读取）
 * @param {string} connID
 * @param {string} name
 * @param {number} lines
 * @returns {$CancellablePromise<string>}
 */
export function GetGuardianLogs(connID, name, lines) {
    return $Call.ByID(3960359431, connID, name, lines);
}

/**
 * GetGuardianStats 获取守护进程统计
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetGuardianStats(connID, name) {
    return $Call.ByID(602001543, connID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetGuardians 获取所有守护进程
 * @param {string} connID
 * @returns {$CancellablePromise<$models.GuardianProcess[]>}
 */
export function GetGuardians(connID) {
    return $Call.ByID(3626911117, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RestartGuardian 重启守护进程
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RestartGuardian(connID, name) {
    return $Call.ByID(3280503143, connID, name);
}

/**
 * StartGuardian 启动守护进程
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function StartGuardian(connID, name) {
    return $Call.ByID(4026581108, connID, name);
}

/**
 * StopGuardian 停止守护进程
 * @param {string} connID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function StopGuardian(connID, name) {
    return $Call.ByID(4121502526, connID, name);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.GuardianProcess.createFrom;
const $$createType2 = $Create.Array($$createType1);
